services:
  # Api Gateway
  kong:
    image: kong:latest
    environment:
      - KONG_DATABASE=off
      - KONG_PROXY_LISTEN=0.0.0:8000
      - KONG_ADMIN_LISTEN=0.0.0:8001
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - sentiment-net

  # Microservices
  auth:
    build: ../sentiment-platform-auth
    environment:
      - MONGO_URI=mongodb://mongo:27017/auth_db
      - KAFKA_BROKER=kafka:9092
      - REDIS_HOST=redis
    depends_on:
      - mongo
      - kafka
      - redis
    networks:
      - sentiment-net

  ingestion:
    build: ../sentiment-platform-ingestion
    environment:
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka
    networks:
      - sentiment-net

  # Infrastructure
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - sentiment-net

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - sentiment-net

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - sentiment-net

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - sentiment-net

networks:
  sentiment-net:
    driver: bridge

volumes:
  mongo-data:
